#!/usr/bin/env php
<?php

set_time_limit(0);
date_default_timezone_set('Europe/London');

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use REBELinBLUE\Sainsburys\Commands\ScrapperCommand;

$application = new Application('Sainsbury\'s Web Scrapper', '1.0.0');
$application->add(new ScrapperCommand);
$application->run();
