#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Sainsbury\'s Web Scrapper', '1.0.0');
//$application->add();

$application->run();
