#!/usr/bin/env php
<?php

// Require the console runner, it is in a seperate file rather than here so that it 
// gets run through the various quality tools as without a .php extension it won't 
require_once __DIR__ . '/src/Console.php';
